# -*- coding: utf-8 -*-
"""
Pydantic schemas for the Kejafi FastAPI backend.

Fixes vs original:
- public_url changed from AnyUrl to str — AnyUrl in Pydantic v2 serializes to
  a URL object, not a plain string, which causes JSON serialization issues and
  breaks the Stage 2 res.get("public_url", "") call.
- Added DeleteResponse for clean DELETE endpoint responses.
- prop.dict() -> prop.model_dump() throughout (Pydantic v2 compat).
"""

from typing import Dict, Optional
from pydantic import BaseModel


class PropertyCreate(BaseModel):
    id: str

    # Core property info
    address: str
    county: str
    metro: str

    # Valuation outputs (from PropertyValuation)
    list_price: float
    noi: float
    cap_rate: float
    irr: float
    equity_multiple: float

    # Metro fundamentals (from metro_lab_core.build_metro_profile)
    pci_2023: Optional[float] = None
    pop_growth: Optional[float] = None
    metro_elasticity: Optional[float] = None
    supply_bucket: Optional[str] = None

    # Risk metrics from metro_lab_core
    risk_score: Optional[float] = None
    risk_bucket: Optional[str] = None

    # Tokenization terms (from Streamlit Step 3)
    token_symbol: str
    token_price: float
    total_supply: int
    lockup_months: int

    # NAV fields (token-ready)
    nav_total: Optional[float] = None
    nav_per_token: Optional[float] = None
    nav_currency: Optional[str] = "USD"

    # AMM / Uniswap guidance
    amm: Optional[str] = None
    quote_asset: Optional[str] = None
    initial_price: Optional[float] = None
    seed_token_amount: Optional[int] = None
    seed_quote_amount: Optional[float] = None
    fee_tier: Optional[float] = None
    price_range_low: Optional[float] = None
    price_range_high: Optional[float] = None

    # Optional on-chain metadata
    token_address: Optional[str] = None
    chain_id: Optional[int] = None
    pool_address: Optional[str] = None


class PropertyOut(PropertyCreate):
    is_published: bool = False
    # FIX: str instead of AnyUrl — AnyUrl in Pydantic v2 returns a URL object
    # that breaks JSON serialization and the Stage 2 res.get("public_url") call.
    public_url: str


class PropertyUpdate(BaseModel):
    """Partial update schema — all fields optional."""
    address: Optional[str] = None
    county: Optional[str] = None
    metro: Optional[str] = None
    list_price: Optional[float] = None
    noi: Optional[float] = None
    cap_rate: Optional[float] = None
    irr: Optional[float] = None
    equity_multiple: Optional[float] = None
    pci_2023: Optional[float] = None
    pop_growth: Optional[float] = None
    metro_elasticity: Optional[float] = None
    supply_bucket: Optional[str] = None
    risk_score: Optional[float] = None
    risk_bucket: Optional[str] = None
    token_symbol: Optional[str] = None
    token_price: Optional[float] = None
    total_supply: Optional[int] = None
    lockup_months: Optional[int] = None
    nav_total: Optional[float] = None
    nav_per_token: Optional[float] = None
    nav_currency: Optional[str] = None
    amm: Optional[str] = None
    quote_asset: Optional[str] = None
    initial_price: Optional[float] = None
    seed_token_amount: Optional[int] = None
    seed_quote_amount: Optional[float] = None
    fee_tier: Optional[float] = None
    price_range_low: Optional[float] = None
    price_range_high: Optional[float] = None
    token_address: Optional[str] = None
    chain_id: Optional[int] = None
    pool_address: Optional[str] = None
    is_published: Optional[bool] = None


class DeleteResponse(BaseModel):
    id: str
    deleted: bool = True


class PropertyDocsIn(BaseModel):
    # Full PPM text generated by TokenizationEngine.generate_offering_memo
    ppm_text: str
    # Cap table JSON exported in Step 4
    cap_table: Dict